import { useEffect, useRef, useState } from 'react'
import { Activity, BarChart3, ChevronRight, Database, FlaskConical, Gauge, Menu, Network, RefreshCw, Server, Settings, ShieldCheck, Upload, X, XCircle } from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts'
import { api, ApiError } from './services/api'

const navItems = [['dashboard', 'Dashboard', Gauge], ['training', 'Federated training', Network], ['analysis', 'TB analysis', FlaskConical], ['results', 'Results', BarChart3], ['settings', 'System details', Settings]]
const titles = { dashboard: 'Dashboard', training: 'Federated training', analysis: 'TB analysis', results: 'Results', settings: 'System details' }
const formatMetric = (value, percent = false) => typeof value === 'number' && Number.isFinite(value) ? (percent ? `${(value * 100).toFixed(1)}%` : value.toFixed(4)) : 'Unavailable'

function Badge({ children, tone = 'neutral' }) { return <span className={`badge badge-${tone}`}>{children}</span> }
function Panel({ title, eyebrow, children }) { return <section className="panel"><div className="panel-heading"><span className="eyebrow">{eyebrow}</span><h2>{title}</h2></div>{children}</section> }
function Loading({ text }) { return <div className="loading" role="status"><span className="spinner" />{text}</div> }
function Empty({ children }) { return <div className="empty">{children}</div> }
function MetricCard({ label, value, detail, icon: Icon }) { return <div className="metric-card"><div className="metric-icon"><Icon size={18} /></div><span>{label}</span><strong>{value}</strong><small>{detail}</small></div> }

function useBackendData() {
  const [data, setData] = useState({ metrics: [], status: null, metadata: null })
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState('')
  const requestActive = useRef(false)
  const load = async () => {
    if (requestActive.current) return
    requestActive.current = true
    try { const [metrics, status, metadata] = await Promise.all([api.metrics(), api.status(), api.metadata()]); setData({ metrics, status, metadata }); setError('') }
    catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Backend unavailable. Make sure the FastAPI server is running.') }
    finally { requestActive.current = false; setLoading(false) }
  }
  useEffect(() => { load(); const timer = setInterval(load, 10000); return () => clearInterval(timer) }, [])
  return { ...data, loading, error, reload: load }
}

function LossChart({ metrics }) {
  if (!metrics.length) return <Empty>No training rounds have been logged yet.</Empty>
  return <div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={metrics}><defs><linearGradient id="lossFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#e07a5f" stopOpacity=".35" /><stop offset="100%" stopColor="#e07a5f" stopOpacity="0" /></linearGradient></defs><CartesianGrid stroke="#26333b" vertical={false} /><XAxis dataKey="round" tickFormatter={(value) => value + 1} stroke="#82919a" /><YAxis stroke="#82919a" /><Tooltip contentStyle={{ background: '#162126', border: '1px solid #34464f' }} formatter={(value) => [Number(value).toFixed(4), 'Total loss']} /><Area type="monotone" dataKey="mean_total_loss" stroke="#e07a5f" fill="url(#lossFill)" strokeWidth={2} /></AreaChart></ResponsiveContainer></div>
}
function Evaluation({ metrics }) {
  const item = [...metrics].reverse().find((entry) => entry.eval_metrics)
  if (!item) return <Empty>Evaluation metrics have not been recorded in the training log.</Empty>
  return <div className="metric-list">{Object.entries(item.eval_metrics).map(([key, value]) => <div key={key}><span>{key.replaceAll('_', ' ')}</span><strong>{formatMetric(value, true)}</strong></div>)}</div>
}

function Dashboard({ model }) {
  const { metrics, status, metadata, loading } = model
  if (loading) return <Loading text="Loading training telemetry" />
  const latest = metrics.at(-1)
  const count = latest?.sample_counts?.reduce((sum, item) => sum + item, 0)
  return <><div className="hero"><div><span className="eyebrow">Federated self-supervised learning</span><h1>Training you can inspect.</h1><p>Operational telemetry for the FedSSL tuberculosis research pipeline.</p></div><Badge tone={status?.state === 'COMPLETED' ? 'success' : 'neutral'}>{status?.state || 'UNKNOWN'}</Badge></div><div className="metric-grid"><MetricCard label="Training loss" value={formatMetric(latest?.mean_total_loss)} detail="Latest logged mean total loss" icon={Activity} /><MetricCard label="Round progress" value={`${status?.completed_rounds ?? 0} / ${status?.total_rounds ?? 'Unavailable'}`} detail="Completed federated rounds" icon={RefreshCw} /><MetricCard label="Hospitals" value={status?.hospital_count ?? 'Unavailable'} detail="Configured participants" icon={Network} /><MetricCard label="Samples in latest round" value={count ?? 'Unavailable'} detail="Across hospital updates" icon={Database} /></div><div className="content-grid"><Panel title="Loss progression" eyebrow="Observed log"><LossChart metrics={metrics} /></Panel><Panel title="Latest round" eyebrow="Federated update">{latest ? <div className="round-summary">{[['Round', latest.round + 1], ['MAE loss', formatMetric(latest.mean_mae_loss)], ['Prototype loss', formatMetric(latest.mean_proto_loss)], ['Aggregation', metadata?.training?.aggregation || 'Unavailable']].map(([name, value]) => <div key={name}><span>{name}</span><strong>{value}</strong></div>)}</div> : <Empty>No round data is available.</Empty>}</Panel></div><Panel title="Evaluation metrics" eyebrow="Montgomery held-out evaluation"><Evaluation metrics={metrics} /></Panel></>
}

function Training({ model }) {
  const { metrics, status, loading, error } = model
  if (loading) return <Loading text="Reading training state" />
  const latest = metrics.at(-1)
  return <><div className="page-intro"><span className="eyebrow">Privacy-preserving coordination</span><h1>Federated training</h1><p>Each hospital trains locally. Only model updates are aggregated by the server.</p></div><div className="process">{[['LOCAL DATA', Database], ['LOCAL TRAINING', Activity], ['MODEL UPDATE', Network], ['AGGREGATION', Server]].map(([label, Icon], index) => <div className="process-step" key={label}><Icon /><span>{label}</span>{index < 3 && <ChevronRight />}</div>)}</div><div className="content-grid"><Panel title="Training lifecycle" eyebrow="Backend status"><div className="lifecycle">{['IDLE', 'STARTING', 'RUNNING', 'COMPLETED'].map((state) => <div className={state === status?.state ? 'current' : ''} key={state}><span>{state}</span>{state === status?.state && <Badge tone="success">Current</Badge>}</div>)}{error && <div className="error-inline">{error}</div>}</div></Panel><Panel title="Hospital participation" eyebrow="Configured participants"><div className="hospital-grid">{Array.from({ length: status?.hospital_count || 0 }, (_, index) => <div className="hospital" key={index}><Database size={17} /><div><strong>Hospital {index + 1}</strong><span>{latest ? 'Update recorded' : 'No update recorded'}</span></div></div>)}</div></Panel></div></>
}

function Analysis() {
  const [file, setFile] = useState(null); const [preview, setPreview] = useState(''); const [result, setResult] = useState(null); const [busy, setBusy] = useState(false); const [error, setError] = useState('')
  const choose = (files) => { const candidate = files?.[0]; if (!candidate) return; if (!['image/png', 'image/jpeg'].includes(candidate.type)) return setError('Choose a PNG or JPG image.'); if (candidate.size > 10 * 1024 * 1024) return setError('The image must be smaller than 10 MB.'); setError(''); setResult(null); setFile(candidate); setPreview(URL.createObjectURL(candidate)) }
  const analyze = async () => { if (!file || busy) return; setBusy(true); setError(''); try { setResult(await api.predict(file)) } catch (reason) { setError(reason instanceof ApiError ? reason.message : 'Prediction failed. Check that the backend model is available.') } finally { setBusy(false) } }
  useEffect(() => () => preview && URL.revokeObjectURL(preview), [preview])
  return <><div className="page-intro"><span className="eyebrow">Canonical few-shot pipeline</span><h1>TB analysis</h1><p>Upload a chest X-ray for a model prediction. This is not a medical diagnosis.</p></div><div className="analysis-grid"><Panel title="X-ray input" eyebrow="PNG or JPG"><label className="dropzone" onDragOver={(event) => event.preventDefault()} onDrop={(event) => { event.preventDefault(); choose(event.dataTransfer.files) }}>{preview ? <img src={preview} alt="Selected chest X-ray preview" /> : <Upload size={30} />}<span>{file ? file.name : 'Drop an image here or choose a file'}</span><input type="file" accept=".png,.jpg,.jpeg" onChange={(event) => choose(event.target.files)} /></label>{file && <div className="file-actions"><button className="button secondary" onClick={() => { setFile(null); setPreview(''); setResult(null) }}><X size={16} />Remove</button><button className="button primary" disabled={busy} onClick={analyze}>{busy ? 'Analyzing...' : 'Analyze image'}</button></div>}{error && <div className="error-box" role="alert"><XCircle size={17} />{error}</div>}</Panel><Panel title="Model prediction" eyebrow="Result"><div aria-live="polite" className="result-area">{busy ? <Loading text="Analyzing X-ray" /> : result ? <><Badge tone={result.prediction === 'TB Positive' ? 'danger' : 'success'}>{result.prediction}</Badge><div className="prediction-value">{result.prediction}</div>{typeof result.tb_probability === 'number' && <div className="probability"><span>TB probability</span><strong>{formatMetric(result.tb_probability, true)}</strong></div>}{typeof result.confidence === 'number' && <div className="probability"><span>Confidence</span><strong>{formatMetric(result.confidence, true)}</strong></div>}<p className="disclaimer">This is an AI model prediction and is not a medical diagnosis.</p></> : <Empty>Select an image, then run analysis.</Empty>}</div></Panel></div></>
}

function Results({ model }) { const { metrics, metadata, loading } = model; if (loading) return <Loading text="Loading evaluation data" />; return <><div className="page-intro"><span className="eyebrow">Research evaluation</span><h1>Results</h1><p>Only metrics emitted by the backend training log are shown.</p></div><Panel title="Held-out evaluation" eyebrow="Montgomery"><Evaluation metrics={metrics} /></Panel><div className="content-grid"><Panel title="Dataset roles" eyebrow="No data leakage"><div className="dataset-list">{Object.entries(metadata?.datasets || {}).map(([name, info]) => <div key={name}><strong>{name}</strong><span>{info.purpose}</span><b>{info.image_count == null ? 'Unavailable' : `${info.image_count} images`}</b></div>)}</div></Panel><Panel title="Few-shot configuration" eyebrow="Shenzhen adaptation"><div className="metric-list"><div><span>Support sampling</span><strong>{metadata?.training?.few_shot_per_class ?? 'Unavailable'}-shot per class</strong></div><div><span>Meaning</span><strong>{metadata?.training?.few_shot_per_class ? `${metadata.training.few_shot_per_class} Normal + ${metadata.training.few_shot_per_class} TB` : 'Unavailable'}</strong></div></div></Panel></div></> }
function SettingsPage({ model }) { const { metadata, status, loading } = model; if (loading) return <Loading text="Loading system details" />; return <><div className="page-intro"><span className="eyebrow">Runtime configuration</span><h1>System details</h1><p>Configuration and model facts reported by the FastAPI service.</p></div><Panel title="Model and federation" eyebrow="Backend metadata"><div className="metric-list">{[['Backbone', metadata?.model?.backbone], ['Classifier', metadata?.model?.classifier], ['Projection dimension', metadata?.model?.projection_dimension], ['Checkpoint', status?.checkpoint?.name || 'Model checkpoint unavailable']].map(([name, value]) => <div key={name}><span>{name}</span><strong>{value ?? 'Unavailable'}</strong></div>)}</div></Panel></> }

export default function App() { const initialPage = window.location.pathname.slice(1); const [page, setPage] = useState(titles[initialPage] ? initialPage : 'dashboard'); const [drawer, setDrawer] = useState(false); const model = useBackendData(); const navigate = (nextPage) => { setPage(nextPage); setDrawer(false); window.history.pushState({}, '', nextPage === 'dashboard' ? '/' : `/${nextPage}`) }; useEffect(() => { const onPopState = () => { const nextPage = window.location.pathname.slice(1); setPage(titles[nextPage] ? nextPage : 'dashboard') }; window.addEventListener('popstate', onPopState); return () => window.removeEventListener('popstate', onPopState) }, []); const Page = { dashboard: Dashboard, training: Training, analysis: Analysis, results: Results, settings: SettingsPage }[page]; const connection = model.loading ? 'Connecting' : model.error ? 'Offline' : 'Connected'; return <div className="app-shell"><aside className={drawer ? 'sidebar open' : 'sidebar'}><div className="brand"><div className="brand-mark"><ShieldCheck size={20} /></div><div><strong>FedSSL</strong><span>TB research console</span></div></div><nav>{navItems.map(([id, label, Icon]) => <button className={page === id ? 'nav-item active' : 'nav-item'} key={id} onClick={() => navigate(id)}><Icon size={18} />{label}</button>)}</nav><div className="sidebar-foot"><span>API connection</span><Badge tone={model.error ? 'danger' : model.loading ? 'neutral' : 'success'}>{connection}</Badge></div></aside><main className="main"><header className="topbar"><button className="icon-button menu-button" aria-label="Open navigation" onClick={() => setDrawer(true)}><Menu size={20} /></button><div><span className="eyebrow">FedSSL / {titles[page]}</span><span className="topbar-note">FastAPI telemetry and canonical model inference</span></div><button className="icon-button" aria-label="Refresh backend data" onClick={model.reload}><RefreshCw size={18} /></button></header>{model.error && <div className="error-banner" role="alert"><XCircle size={18} />{model.error}</div>}<div className="page"><Page model={model} /></div></main>{drawer && <button className="scrim" aria-label="Close navigation" onClick={() => setDrawer(false)} />}</div> }
